Library/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LibraryData;
using LibraryData.Models;
using Library.Models.Branch;

namespace Library.Controllers
{
    public class BranchController : Controller
    {
        private ILibraryBranch _branch;
        public BranchController(ILibraryBranch branch)
        {
            _branch = branch;
        }

        public IActionResult Index()
        {
            var branches = _branch.GetAll().Select(branch => new BranchDetailModel
            {
                Id = branch.Id,
                Name = branch.Name,
                isOpen = _branch.IsBranchOpen(branch.Id),
                NumberOfAssets = _branch.GetAssets(branch.Id).Count(),
                NumberOfPatrons = _branch.GetPatrons(branch.Id).Count()
            });
            var model = new BranchIndexModel()
            {
                Branches = branches
            };
            return View(model);
        }
        public IActionResult Detail(int id)
        {
            var branch = _branch.Get(id);
            var model = new BranchDetailModel
            {

                Id = branch.Id,
                Name = branch.Name,
                isOpen = _branch.IsBranchOpen(branch.Id),
                OpenDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfAssets = _branch.GetAssets(branch.Id).Count(),
                NumberOfPatrons = _branch.GetPatrons(branch.Id).Count(),
                TotalAssetValue = _branch.GetAssets(id).Sum(a => a.Cost),
                ImageUrl = branch.ImageUrl,
                Address = branch.Address,
                Description = branch.Description,
                Telephone = branch.Telephone,
                HoursOpen = _branch.GetBrachHours(id)
            };

            return View(model);

        }
    }
}

Library/Controllers/CatalogController.cs
using Library.Models.Catalog;
using Library.Models.Catalog.CheckoutModels;
using LibraryData;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class CatalogController:Controller
    {

        private ILibraryAsset _asset;
        private ICheckout _checkouts;
        public CatalogController(ILibraryAsset asset, ICheckout checkouts)
        {
            _asset = asset;
            _checkouts = checkouts;
        }
        public IActionResult Index()
        {
            var assetModels = _asset.GetAll();
            var listingResult = assetModels
                .Select(result => new AssetIndexListingModel
                {
                    Id = result.Id,
                    ImageUrl = result.ImageUrl,
                    AuthorOrDirector = _asset.GetAuthorOrDirector(result.Id),
                    DeweyCallNumber = _asset.GetDeweyIndex(result.Id),
                    Title = result.Title,
                    Type = _asset.GetType(result.Id)

                });
            var model = new AssetIndexModel()
            {
                Assets = listingResult
            };

            return View(model);
        }


        public  IActionResult Portofolio()
        {
            return View();
        }
       
        public IActionResult Details(int id)
        {
            var asset = _asset.GetById(id);
            var currentHolds = _checkouts.GetCurrentHolds(id).Select(a => new AssetHoldModel()
            {
                HoldPlaced = _checkouts.GetCurrentHoldPlaced(a.Id),
                PatronName = _checkouts.GetCurrentHoldPatronName(a.Id)

            });
            
            var assetmodel = new AssetDetailModel
            {

                AssetId = id ,
                Title = asset.Title,
                Type = _asset.GetType(id),
                Year = asset.Year,
                Cost = asset.Cost,
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _asset.GetAuthorOrDirector(id),
                CurrentLocation = _asset.GetCurrentLocation(id).Name,
                DeweyCallNumber = _asset.GetDeweyIndex(id),
                ISBN = _asset.GetIsbn(id),
                CheckoutHistory = _checkouts.GetCheckoutHistory(id),
                LatestCheckout = _checkouts.GetLatestCheckout(id),
                PatronName = _checkouts.GetCurrentCheckoutPatron(id),
                CurrentHolds = currentHolds
               
            };
            return View(assetmodel);
        }




        public  IActionResult Checkout(int id)
        {
            var asset = _asset.GetById(id);
            var model = new CheckoutModel
            {
                AssetId =id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId ="",
                IsCheckedOut = _checkouts.IsCheckedOut(id)
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult PlaceCheckout(int assetId, int libraryCardId)
        {
            _checkouts.CheckOutItem(assetId, libraryCardId);
            return RedirectToAction("Details", new { id = assetId });
        }
        public IActionResult MarkLost(int assetId)
        {
            _checkouts.MarkLost(assetId);
            return RedirectToAction("Details", new { id = assetId });
            
        }
        public IActionResult Hold(int id)
        {
            var asset = _asset.GetById(id);
            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = _checkouts.IsCheckedOut(id),
                HoldCount = _checkouts.GetCurrentHolds(id).Count()
            };
            return View(model);
        }
        public IActionResult MarkFound(int assetId)
        {
            _checkouts.MarkLost(assetId);
            return RedirectToAction("Details", new { id = assetId });
        }

       
        [HttpPost]
        public IActionResult PlaceHold(int assetId, int libraryCardId)
        {
            _checkouts.PlaceHold(assetId, libraryCardId);
            return RedirectToAction("Details", new { id = assetId });
        }

        public IActionResult Checkin( int id)
        {
            _checkouts.CheckInItem(id);
            return RedirectToAction("Details", new { id = id });
        }
    }
}

Library/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Models.Patron;
using LibraryData;
using LibraryData.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class PatronController : Controller
    {
        private IPatron _patron;
        public PatronController(IPatron patron)
        {
            _patron = patron;
        }
        public IActionResult Index()
        {
            var allPatrons = _patron.GetAll();
           // View(allPatrons);
            var patronModels = allPatrons.Select(p => new PatronDetailModel
            {
                Id = p.Id,
                FirstName = p.FirstName,
                LastName = p.LastName,
                LibraryCardId = p.LibraryCard.Id,
                OverdueFees =p.LibraryCard.Fees,
                HomeLibraryBranch = p.HomeLibraryBranch.Name

            }).ToList();
            var model = new PatronIndexModel
            {
                Patrons = patronModels
            };
            return View(model);
        }
       public IActionResult Details (int id)
        {
            var patron = _patron.Get(id);
            var model = new PatronDetailModel
            {

                FirstName = patron.FirstName,
                LastName = patron.LastName,
                LibraryCardId = patron.LibraryCard.Id,
                OverdueFees = patron.LibraryCard.Fees,
                HomeLibraryBranch = patron.HomeLibraryBranch.Name,
                MemberSince = patron.LibraryCard.Created,
                Address = patron.Address,
                Telephone = patron.TelephoneNumber,
                assetsCheckedOut = _patron.GetCheckouts(id).ToList() ?? new List<Checkout>(),
                CheckoutHistory = _patron.GetCheckoutHistory(id),
                Holds = _patron.GetHolds(id)


            };
            return View(model);
        }
    }

}

Library/Views/Shared/_Footer.cshtml
<footer class="mdl-mini-footer">
    <div class="mdl-mini-footer__left-section">
        <div class="mdl-logo">Title</div>
        <ul class="mdl-mini-footer__link-list">
            <li><a href="#">Help</a></li>
            <li><a href="#">Privacy & Terms</a></li>
        </ul>
    </div>
</footer>

Library/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Library Gentofte</title>
    <link rel="shortcut icon" href="images/favicon.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>


</head>
<body>


    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">Gentofte -Libray Management</span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                    <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patron</a>
                    <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branch</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Title</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patron</a>
                <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branch</a>
            </nav>
        </div>
        <main class="mdl-layout__content">
            <div class="page-content">
                @RenderBody()
                @Html.Partial("_Footer")
            </div>
        </main>
    </div>


    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    @RenderSection("scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>

Library/Views/Shared/_LayoutMain.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Library Gentofte</title>
    <link rel="shortcut icon" href="images/favicon.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/main.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>


</head>
<body >


    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">Libray Management System</span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                    <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patron</a>
                    <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branch</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Title</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patron</a>
                <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branch</a>
            </nav>
        </div>
        <div class="container">
            <div class="page-content">
                @RenderBody()
                <!-- @Html.Partial("_Footer")-->
            </div>
        </div>
    </div>


    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    @RenderSection("scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>